### ISSUE TITLE
Missing Files in the Uploaded EFSAll

### ISSUE THREAD

**Issue by JoeLeelyf** [YZY-stack/DF40#16]
I noticed that several samples are missing in your uploaded files, especially in the EFS family, including ddim/rddm/VQGAN/StyleGAN...
![Screenshot 2024-10-19 at 17 07 43](https://github.com/user-attachments/assets/86d4738d-0ebe-4ecc-89eb-d8e9632f4ae6)

**Comment by YZY-stack** [comment]
Thanks for your kind mention. Please note that **for EFS methods, this situation is normal** because DeepfakeBench organizes its file directories hierarchically by folder, video-name, and frame-name. However, the EFS methods generate images by starting from noise, and we didn't place them into their respective video-name folders. Instead, we aimed to include up to 32 frames in each video folder. 

Due to variations in the real data, some videos may not have reached the full 32 frames (e.g., due to profile shots), resulting in some video folders lacking frames in the EFS setup. Nevertheless, the overall number of frames should still correspond to the real data.

**Comment by JoeLeelyf** [comment]
So can we just leave these "missing files" out if we are certain that we have downloaded the right files?

**Comment by YZY-stack** [comment]
Yes, you can. I will update a new version of the JSON files without these "missing files". Thanks for your question.

**Comment by JoeLeelyf** [comment]
Thanks for that, and please inform me in this issue if you have uploaded the refreshed JSON files.

**Comment by YZY-stack** [comment]
Hi @JoeLeelyf, I have updated the JSON files without the "missing files." Please check this [link](https://drive.google.com/drive/folders/1rh-82Rn0pqQ7xzLDKBv9gdjy-sbxYC8-?usp=sharing).

**Comment by JoeLeelyf** [comment]
Thanks for your timely response :)

**Comment by JoeLeelyf** [comment]
I found the problem exists in the newly uploaded JSON file for StyleGAN*_ff/SiT_ff/DiT_ff.json....
Some directory in JSON file dose not seems to appear in the uploaded zip file.
<img width="983" alt="Screenshot 2024-10-26 at 21 45 12" src="https://github.com/user-attachments/assets/9c8ec436-146b-46bd-9963-3951df23d89f">
<img width="708" alt="Screenshot 2024-10-26 at 21 46 11" src="https://github.com/user-attachments/assets/51a5a7c2-4b2f-470e-a9da-440cdad19a39">
