### ISSUE TITLE
I am confused about dataset files.

### ISSUE THREAD

**Issue by NAHOHYUN-SKKU** [YZY-stack/DF40#25]
1. I found that real data is duplicated in the FSAll json file. If I train the Xception model for 1 epoch using the FSAll_ff.json file, will the real data be trained multiple times while the fake data is trained once?

2. The paper says that the dataset created with the e4e method is used for train&test. However, there is no e4e file in the training folder. In the json folder, unlike other methods, there are three json files: e4e_ff, e4e_cdf, and e4e, so I'm confused about which one is correct. Even among them, the e4e_ff.json file has the same fake data for training and test.

**Comment by NAHOHYUN-SKKU** [comment]
Additionally, after downloading all the datasets and pretrained model weights, I ran the training code in the Example, but I got an error related to DDP. This problem occurs regardless of whether it is a multi-gpu or single-gpu training code.

`python training/train.py --detector_path ./training/config/detector/xception.yaml --train_dataset FSAll_ff --test_dataset FSAll_ff`

```
Traceback (most recent call last):
  File "/home/hohyun/DF_foundation/DF40/DeepfakeBench_DF40/training/train.py", line 287, in <module>
    main()
  File "/home/hohyun/DF_foundation/DF40/DeepfakeBench_DF40/training/train.py", line 219, in main
    logger.info('Save log to {}'.format(logger_path))
  File "/home/hohyun/anaconda3/envs/df40/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
  File "/home/hohyun/anaconda3/envs/df40/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/home/hohyun/anaconda3/envs/df40/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/home/hohyun/anaconda3/envs/df40/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/home/hohyun/anaconda3/envs/df40/lib/python3.10/logging/__init__.py", line 964, in handle
    rv = self.filter(record)
  File "/home/hohyun/anaconda3/envs/df40/lib/python3.10/logging/__init__.py", line 821, in filter
    result = f.filter(record)
  File "/home/hohyun/DF_foundation/DF40/DeepfakeBench_DF40/training/logger.py", line 11, in filter
    return dist.get_rank() == self.rank
  File "/home/hohyun/anaconda3/envs/df40/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 844, in get_rank
    default_pg = _get_default_group()
  File "/home/hohyun/anaconda3/envs/df40/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 429, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

**Comment by YZY-stack** [comment]
@NAHOHYUN-SKKU  Thanks very much for using DF40. I summarize your issues into the following three separate points:

1. **About the ratio of real and fake data:**
   * In DF40, we have implemented multiple fake generators to create fake data using the same original data (e.g., FF++). So the ratio of real and fake can be highly imbalanced. If you use 30 fake methods for training, it will result in a 30: 1 ratio of fake and real. To overcome the imbalance issue in the deepfake detection field, we note that several previous works have tried to repeatedly use the real data multiple times to balance the fake data and make the ratio to be 1: 1, as shown in section 4.1 of the F3Net paper (ECCV 2020). We, in DF40, follow these existing works to balance the real and fake data.
   * Note that, the word "duplicated" might not be completely correct in your description. This is because we will apply data augmentation to process each input frame. Although we repeatedly use the same real frame, different augmentations will make it look different, not duplicated.
   * If you find a better solution to address the imbalance problem, I am very happy to discuss it with you.

2. **About e4e:**
   * I am sorry for the confusion. The e4e is created within both the FF++ domain and the CDF domain. This aligns with other methods such as simswap. So you can perform training on e4e (FF) and testing on simswap (FF) for the cross-method evaluation.
   * However, I do not put the e4e into the training set and do not perform training on e4e, as the e4e often generates a very high-resolution image, which is significantly different than those of original real images (relatively blurry). In the analysis section of our paper, we highlight this resolution gap between real and fake classes can lead the detectors to learn the spurious correlation and resolution bias, limiting its potential to learn a more general artifact. In a word, our DF40 supports you perform training on e4e, but we do not recommend you to do so, in order to avoid the resolution bias.
   * For the "JSON files", we have updated the e4e_ff.json (JSON) and e4e.zip (dataset) for better clarification, and removed the no-used "e4e.json". Please try them for better usage. Now, you can use e4e as the same as other methods like simswap.
   
3. **Mentioned DDP Issue:**
   * I cannot understand why you will encounter that problem. If you use the following command: `python training/train.py --detector_path ./training/config/detector/xception.yaml --train_dataset FSAll_ff --test_dataset FSAll_ff`, you will not use the DDP mode. But your bugs seem you have encountered the DDP issue. Can you please provide more information about this so that I can help you solve it?
